version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  inventoryservice:
    build: ./InventoryService
    container_name: inventoryservice
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq

  salesservice:
    build: ./SalesService
    container_name: salesservice
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq

  apigateway:
    build: ./ApiGateway
    container_name: apigateway
    ports:
      - "5000:80"
    depends_on:
      - inventoryservice
      - salesservice